### PR TITLE
Run kojid using systemd service file

### PR DESCRIPTION
**Pull request by vrutkovs**

### CODE REVIEW

**Comment by lcarva** [comment]
Is this based on this https://developers.redhat.com/blog/2016/09/13/running-systemd-in-a-non-privileged-container/ ?

**Comment by vrutkovs** [comment]
Yep. This kinda binds this to Fedora-/ RHEL-based hosts for now though

**Comment by lcarva** [comment]
Is this needed then? If it's to make sure that the ansible playbook can run cleanly against it, you can simply run with: `-e "koji_builder_skip_handlers=true"`

But this won't actually restart what's needed to pick up changes. Still need to restart container.
And I just talked myself into agreeing on this change.

**Comment by vrutkovs** [comment]
It might be pretty useful - e.g. update osbs-client on the builder and restart the service without bringing down the whole container

Also, `skip_handlers` is not really fair

**Pull request merged**
