### PR TITLE
Finalize web.conf on up

### PR DESCRIPTION
**Pull request by bfontecc007**
This is to change the config file in accordance with https://github.com/lcarva/osbs-box/issues/37

### CODE REVIEW

**Comment by lcarva** [comment]
Replacement needs to happen at container run time. `hub/bin/setup.sh` looks like a good candidate.

**Comment by lcarva** [comment]
@bfontecc007 do you plan on continuing work on this issue?

**Comment by bfontecc007** [comment]
Yes I'll get to it.

**Comment by lcarva** [comment]
Things have changed quite a bit since this PR was introduced. Closing it for now to give others a chance to address it too.

**Pull request closed without merging**
